apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "three-tier.fullname" . }}-db-migration-{{ .Release.Revision }}
  # Release.revision to maintain unique job name for each revision of the helm chart 
  
  labels:
    {{- include "three-tier.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: migration
        azure.workload.identity/use: "true"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Release.Name }}-api-sa
      containers:
        - name: db-migration-task
          image: python:3.11-alpine
          command:
            - "sh"
            - "-c"
            - |
              DB_USER=$(cat /mnt/secrets-store/db-user)
              DB_PASSWORD=$(cat /mnt/secrets-store/db-password)
              DB_NAME=$(cat /mnt/secrets-store/db-name)

              echo "Connecting to MySQL at $DB_HOST:$DB_PORT as user $DB_USER..."
              echo "Applying database schema migrations to database $DB_NAME..."
              # this is just a simulation that I have added... In most scenarios we would usually connect to an external db and run the migration scripts. 
              # But since we are using a local db, I am just simulating the migration process here.
              sleep 3
              echo "Migration complete."
          env:
            - name: DB_HOST
              value: "{{ include "three-tier.fullname" . }}-database"
            - name: DB_PORT
              value: "{{ .Values.database.service.port }}"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ include "three-tier.fullname" . }}-kv-sync"