apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "three-tier.fullname" . }}-kv-sync
  labels:
    {{- include "three-tier.labels" . | nindent 4 }}
    
  # Because pre-install hooks run before standard manifests are created, Helm needs the SecretProviderClass and ServiceAccount to exist when the hook executes.
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.global.azureWorkloadClientId | quote }}
    keyvaultName: {{ .Values.global.keyVaultName | quote }}
    tenantId: {{ .Values.global.azureTenantId | quote }}
    objects: |
      array:
        - |
          objectName: db-user
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
  secretObjects:
    - secretName: db-credentials-synced
      type: Opaque
      data:
        - objectName: db-user
          key: DB_USER
        - objectName: db-password
          key: DB_PASSWORD
        - objectName: db-name
          key: DB_NAME