apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-api-sa
  # Because pre-install hooks run before standard manifests are created, Helm needs the SecretProviderClass and ServiceAccount to exist when the hook executes.
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    azure.workload.identity/client-id: {{ .Values.global.azureWorkloadClientId | quote }}
  labels:
    azure.workload.identity/use: "true"
    